### ISSUE TITLE
cuda/extras/CUPTI/include/cupti_result.h relocated in CUDA11.1

### ISSUE THREAD

**Issue by Godricly** [google/nvidia_libs_test#11]
this file is relocated under /usr/local/cuda in CUDA 11.1(installed from local deb.) 
```
cuda_util.h:26:10: fatal error: cuda/extras/CUPTI/include/cupti_result.h: No such file or directory
 #include "cuda/extras/CUPTI/include/cupti_result.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //:cudnn_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

**Comment by chsigg** [comment]
Yeah, the header file locations are moving around quite a bit, both for the CUDA toolkit installer and the deb packages. 

nvidia_libs_test expects that the CUDA toolkit and cuDNN are both self-contained in a directory. Everything else ends up pretty complicated, see e.g. TensorFlow's find_cuda_config.py.

I would recommend running the CUDA toolkit installer and extracting everything to a single directory through command line arguments, instead of using the deb package.
